export const CREATE_TEAM = 'CREATE_TEAM';
export const JOIN_TEAM = 'JOIN_TEAM';
// TODO: Error handling for failure.
export const CREATE_TEAM_SUCCESS = 'CREATE_TEAM_SUCCESS';


export const FETCH_SERVICE_REQUESTS = 'FETCH_SERVICE_REQUESTS';
export const FETCH_SERVICE_REQUESTS_SUCCESS = 'FETCH_SERVICE_REQUESTS_SUCCESS';
export const FETCH_SERVICE_REQUESTS_FAILURE = 'FETCH_SERVICE_REQUESTS_FAILURE';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';