export const FETCH_GENERAL_CANVASSING_REQUEST = 'FETCH_GENERAL_CANVASSING_REQUEST';
export const FETCH_GENERAL_CANVASSING_SUCCESS = 'FETCH_GENERAL_CANVASSING_SUCCESS';
export const FETCH_GENERAL_CANVASSING_FAILURE = 'FETCH_GENERAL_CANVASSING_FAILURE';

export const FETCH_INTENSIVE_CANVASSING_REQUEST = 'FETCH_INTENSIVE_CANVASSING_REQUEST';
export const FETCH_INTENSIVE_CANVASSING_SUCCESS = 'FETCH_INTENSIVE_CANVASSING_SUCCESS';
export const FETCH_INTENSIVE_CANVASSING_FAILURE = 'FETCH_INTENSIVE_CANVASSING_FAILURE';

export const FETCH_JOINT_OPERATIONS_REQUEST = 'FETCH_JOINT_OPERATIONS_REQUEST';
export const FETCH_JOINT_OPERATIONS_SUCCESS = 'FETCH_JOINT_OPERATIONS_SUCCESS';
export const FETCH_JOINT_OPERATIONS_FAILURE = 'FETCH_JOINT_OPERATIONS_FAILURE';

export const FETCH_PANHANDLING_REQUEST = 'FETCH_PANHANDLING_REQUEST';
export const FETCH_PANHANDLING_SUCCESS = 'FETCH_PANHANDLING_SUCCESS';
export const FETCH_PANHANDLING_FAILURE = 'FETCH_PANHANDLING_FAILURE';


