import { RESOLVE_SERVICE_REQUEST, UPDATE_ONSITE_STATUS } from '../serviceRequests/actionTypes';

export const ADD_TO_SYNC_QUEUE = 'ADD_TO_SYNC_QUEUE';
export const FINISH_SYNC = 'FINISH_SYNC';
export const SYNC_SERVICE_REQUESTS = 'SYNC_SERVICE_REQUESTS';
export const NETWORK_STATUS_CHANGE = 'NETWORK_STATUS_CHANGE';

export const QUEUEABLE_ACTIONS = [
  UPDATE_ONSITE_STATUS,
  RESOLVE_SERVICE_REQUEST,
];