# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProviderResponseApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ProviderResponseApp
  pod 'Fabric'
  pod 'Crashlytics'

  # pod 'React', path: '../node_modules/react-native', :subspecs => [
  #   'Core',
  #   'RCTActionSheet',
  #   'RCTAnimation',
  #   'RCTGeolocation',
  #   'RCTImage',
  #   'RCTLinkingIOS',
  #   'RCTNetwork',
  #   'RCTSettings',
  #   'RCTText',
  #   'RCTVibration',
  #   'RCTWebSocket'
  # ]
  pod 'GoogleMaps'

  target 'ProviderResponseAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
