# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version '2.3.0'

default_platform :ios

platform :ios do
  desc 'Staging Builds'
  lane :staging do
    cert
    sigh(app_identifier: 'gov.nyc.dhs.providerresponse.staging')
    increment_build_number(xcodeproj: './ios/ProviderResponseApp.xcodeproj')
    gym(
      clean: true,
      scheme: 'ProviderResponseApp-Staging',
      project: './ios/ProviderResponseApp.xcodeproj'
    )
    pilot(
      skip_waiting_for_build_processing: true,
      app_identifier: 'gov.nyc.dhs.providerresponse.staging'
    )
  end


  desc 'Beta Builds'
  lane :beta do
    cert
    sigh
    increment_build_number(xcodeproj: './ios/ProviderResponseApp.xcodeproj')
    gym(
      clean: true,
      scheme: 'ProviderResponseApp-Production',
      project: './ios/ProviderResponseApp.xcodeproj'
    )
    pilot(skip_waiting_for_build_processing: true)
  end
end

platform :android do
  desc 'Deploy to crashlytics (staging)'
  lane :staging do
    version_file = '../android/version_code'
    version_code = File.read(version_file).to_i
    version_code += 1

    f = File.new(version_file, 'w')
    f.write(version_code)
    f.close

    gradle(
      project_dir: 'android',
      task: 'assemble',
      build_type: 'Staging',
      properties: { versionCode: version_code }
    )
    crashlytics(
      groups: ['testers'],
      api_token: ENV['CRASHLYTICS_API_TOKEN'],
      build_secret: ENV['CRASHLYTICS_BUILD_SECRET']
    )
  end

  desc 'Deploy to crashlytics (production)'
  lane :beta do
    version_file = '../android/version_code'
    version_code = File.read(version_file).to_i
    version_code += 1

    f = File.new(version_file, 'w')
    f.write(version_code)
    f.close

    gradle(
      project_dir: 'android',
      task: 'assemble',
      build_type: 'Release',
      properties: { versionCode: version_code }
    )
    crashlytics(
      groups: ['testers'],
      api_token: ENV['CRASHLYTICS_API_TOKEN'],
      build_secret: ENV['CRASHLYTICS_BUILD_SECRET']
    )
  end
end
