export const FETCH_RESOLUTION_CODES = 'FETCH_RESOLUTION_CODES';
export const FETCH_RESOLUTION_CODES_SUCCESS = 'FETCH_RESOLUTION_CODES_SUCCESS';
export const FETCH_RESOLUTION_CODES_FAILURE = 'FETCH_RESOLUTION_CODES_FAILURE';

export const FETCH_SERVICE_REQUESTS = 'FETCH_SERVICE_REQUESTS';
export const FETCH_SERVICE_REQUESTS_SUCCESS = 'FETCH_SERVICE_REQUESTS_SUCCESS';
export const FETCH_SERVICE_REQUESTS_FAILURE = 'FETCH_SERVICE_REQUESTS_FAILURE';

export const FETCH_SERVICE_REQUEST_DETAILS = 'FETCH_SERVICE_REQUEST_DETAILS';
export const FETCH_SERVICE_REQUEST_DETAILS_SUCCESS = 'FETCH_SERVICE_REQUEST_DETAILS_SUCCESS';
export const FETCH_SERVICE_REQUEST_DETAILS_FAILURE = 'FETCH_SERVICE_REQUEST_DETAILS_FAILURE';

export const RESOLVE_SERVICE_REQUEST = 'RESOLVE_SERVICE_REQUEST';
export const RESOLVE_SERVICE_REQUEST_SUCCESS = 'RESOLVE_SERVICE_REQUEST_SUCCESS';
export const RESOLVE_SERVICE_REQUEST_FAILURE = 'RESOLVE_SERVICE_REQUEST_FAILURE';

export const SELECT_SERVICE_REQUEST = 'SELECT_SERVICE_REQUEST';
export const SELECT_SERVICE_REQUEST_RESOLUTION = 'SELECT_SERVICE_REQUEST_RESOLUTION';

export const UPDATE_ONSITE_STATUS = 'UPDATE_ONSITE_STATUS';
export const UPDATE_ONSITE_STATUS_SUCCESS = 'UPDATE_ONSITE_STATUS_SUCCESS';
export const UPDATE_ONSITE_STATUS_FAILURE = 'UPDATE_ONSITE_STATUS_FAILURE';

export const ADD_CONTACT_TO_SERVICE_REQUEST = 'ADD_CONTACT_TO_SERVICE_REQUEST';

export const FILTER_URGENT_SERVICE_REQUESTS = 'FILTER_URGENT_SERVICE_REQUESTS';
export const MARK_URGENT_SERVICE_REQUEST_READ = 'MARK_URGENT_SERVICE_REQUEST_READ';