export const FETCH_SERVICE_REQUESTS = 'FETCH_SERVICE_REQUESTS';
export const FETCH_SERVICE_REQUESTS_SUCCESS = 'FETCH_SERVICE_REQUESTS_SUCCESS';
export const FETCH_SERVICE_REQUESTS_FAILURE = 'FETCH_SERVICE_REQUESTS_FAILURE';

export const FETCH_SERVICE_REQUEST_DETAILS = 'FETCH_SERVICE_REQUEST_DETAILS';

export const RESOLVE_SERVICE_REQUEST = 'RESOLVE_SERVICE_REQUEST';
export const RESOLVE_SERVICE_REQUEST_SUCCESS = 'RESOLVE_SERVICE_REQUEST_SUCCESS';
export const RESOLVE_SERVICE_REQUEST_FAILURE = 'RESOLVE_SERVICE_REQUEST_FAILURE';

export const SELECT_SERVICE_REQUEST = 'SELECT_SERVICE_REQUEST';
export const SELECT_SERVICE_REQUEST_RESOLUTION = 'SELECT_SERVICE_REQUEST_RESOLUTION';

export const UPDATE_ONSITE_STATUS = 'UPDATE_ONSITE_STATUS';
export const UPDATE_ONSITE_STATUS_SUCCESS = 'UPDATE_ONSITE_STATUS_SUCCESS';
export const UPDATE_ONSITE_STATUS_FAILURE = 'UPDATE_ONSITE_STATUS_FAILURE';

export const MARK_PENDING_STATUS = 'MARK_PENDING_STATUS';

export const ADD_CONTACT_TO_SERVICE_REQUEST = 'ADD_CONTACT_TO_SERVICE_REQUEST';

export const RERENDER_SERVICE_REQUESTS = 'RERENDER_SERVICE_REQUESTS';

export const FILTER_URGENT_SERVICE_REQUESTS = 'FILTER_URGENT_SERVICE_REQUESTS';
export const MARK_URGENT_SERVICE_REQUEST_READ = 'MARK_URGENT_SERVICE_REQUEST_READ';
export const UPDATE_SERVICE_REQUESTS_WITH_NOTES = 'UPDATE_SERVICE_REQUESTS_WITH_NOTES';

export const UPDATE_RESOLUTION_NOTES = 'UPDATE_RESOLUTION_NOTES';

export const UPDATE_PING_RESPONSE = 'UPDATE_PING_RESPONSE';


export const RESOLUTION_CODES = {
  assistance_offered: 1,
  insufficient_information: 2,
  person_not_found: 3,
  referred_to_911: 4,
  refused_assistance: 5,
  out_of_provider_network: 6,
};
