export const FETCH_SERVICE_REQUESTS = 'FETCH_SERVICE_REQUESTS';
export const FETCH_SERVICE_REQUESTS_SUCCESS = 'FETCH_SERVICE_REQUESTS_SUCCESS';
export const FETCH_SERVICE_REQUESTS_FAILURE = 'FETCH_SERVICE_REQUESTS_FAILURE';
