export const CREATE_TEAM = 'CREATE_TEAM';
export const CREATE_TEAM_SUCCESS = 'CREATE_TEAM_SUCCESS';

export const FETCH_CURRENT_TEAM = 'FETCH_CURRENT_TEAM';
export const FETCH_CURRENT_TEAM_SUCCESS = 'FETCH_CURRENT_TEAM_SUCCESS';

export const FETCH_TEAMS = 'FETCH_TEAMS';
export const FETCH_TEAMS_SUCCESS = 'FETCH_TEAMS_SUCCESS';

export const FETCH_TEAM_USERS = 'FETCH_TEAM_USERS';
export const FETCH_TEAM_USERS_SUCCESS = 'FETCH_TEAM_USERS_SUCCESS';

export const JOIN_TEAM = 'JOIN_TEAM';
export const JOIN_TEAM_SUCCESS = 'JOIN_TEAM_SUCCESS';

export const LEAVE_TEAM = 'LEAVE_TEAM';
export const LEAVE_TEAM_SUCCESS = 'LEAVE_TEAM_SUCCESS';

export const SELECT_TEAM = 'SELECT_TEAM';